#!/bin/bash
find ~/.dotfiles -name ".*" -type f -maxdepth 1 | xargs -I {} ln -sv {} ~
ln -sv ~/.dotfiles/.bin/ ~
find ~/.dotfiles/.bin/ -type f -maxdepth 1 | xargs chmod +x
mv ~/.dotfiles/main.terminal ~
