#!/usr/bin/env bash
A='\033[0;37m\033[7m' # gray BG, dark gray text
B='\033[0;33m\033[1m' # gold, bold text
C='\033[0;37m' # gray text
D='\033[5m'

echo
echo -n -e "  ${A} TERMINAL ${B} CORY McCARTAN ${C} "
date +"%l:%M %p %A, %B %e, %Y" 
echo 
