#!/usr/bin/env bash

# update App Store apps
sudo softwareupdate -i -a

# Update Homebrew (Cask) & packages
brew update 
touch ~/.bin/.tmp/brew-updates
brew upgrade | tee ~/.bin/.tmp/brew-updates

# Update npm & packages
npm install npm -g
touch ~/.bin/.tmp/npm-updates
npm update -g | tee ~/.bin/.tmp/npm-updates

echo
echo "==== SUMMARY ===="
echo
cat ~/.bin/.tmp/brew-updates | grep -e "Installing|Upgrading"
cat ~/.bin/.tmp/npm-updates | grep -e "Installing|Upgrading"
echo
